# Site
repository: Brian-Morse/project_website
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Brian Morse
title: UCSD Student
email: mybrianmorse@gmail.com
website: brian-morse.github.io/project_website

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  Brian-Morse
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: brian-morse-157553288
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: MorseBrian.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Brian. I am a current UC San Diego student majoring in computer science. Proud to be a Triton! Besides my formal studies, I am an Eagle Scout and really enjoy bowling whenever possible.

  My top skills are: <mark>Software Engineering</mark>, <mark>Leadership</mark>, <mark>Self-motivation</mark>, and <mark>Organization</mark>

  I hope to get a job in the programming field with a possible specialization in artificial intelligence but I am open to more areas of work

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: FundNeighbors
        link: github.com/Brian-Morse/FundNeighbors
        quote: >
          A central hub of fundraisers to increase awareness and success of fundraisers held by schools and clubs
        description: |
          In a cooperative effort with my father, I was the sole developer of the front-end capabilities of the FundNeighbors website. It was my first time making a fully usable website with the intent to be used. This website was developed by taking advantage of the Next.js libraries. The site has many features including searching, CRUD actions on events, a login system, and database manipulation. I improved my knowledge of web development, deployment, and debugging tough web complications.
      
      - layout: top-middle
        title: Developer Journal
        link: github.com/cse110-sp24-group2/cse110-sp24-group2
        quote: >
          Developer Journal app that can be installed and used to track work done by a software engineer
        description: |
          I was a team leader in this group project for a course at UCSD. It includes a navigation calendar, a markdown editor, a search mechanism, and a to-do list. The project mainly focused on the development processes (Agile, Git Best Practices, etc.) and getting comfortable with web tools and languages. As a leader, I also had to coordinate meetings and provide guidance to the other ten members of the team. I learned to balance those needs while still creating good code myself.
    
      - layout: top-middle
        title: YouTube Game Reviewer
        link: github.com/acmucsd-projects/fa23-podmates-ai-team-1
        # link_text: Project Website
        quote: >
          Sentiment Analysis AI model that rates games based on YouTube Comments
        description: | # this will include new lines to allow paragraphs
          I participated as one of the lead developers in a team of six to develop this AI model and Chrome extension. When on a YouTube link and is activated, the Chrome extension will analyze the top 100 comments to get an understanding of the feeling about the video game that the video discusses and convey a percentage score and the top three feelings

    
      - layout: top-middle
        title: Chess
        link: github.com/Brian-Morse/Chess
        # link_text: Project Website
        quote: >
          This is an interactive two-player chess game written using Python
        description: | # this will include new lines to allow paragraphs
          I started this project as a way to learn Python but continued to work on it to solve many problems of design and logical movements. I enjoy playing chess so finding a way to incorporate all the rules was extremely interesting and fun

      - layout: top-middle
        title: Nonogram Puzzle Solver
        link: github.com/Brian-Morse/nonogramsolver
        quote: >
          This can solve any sized Nonogram puzzle and was written using Java
        description: |
          In an attempt to learn about how to make a basic artificial intelligence that can solve a puzzle, I found that I was playing Nonogram almost every day, so I decided to tackle it. It became a very intriguing project as I found and researched new ways to quickly find the solution without using any brute force

      - layout: top-middle
        title: 2048 Game
        link: github.com/Brian-Morse/2048
        quote: >
          A custom-sized 2048 game with persistent high score tracking, written using Java
        description: |
          Since I wanted to learn about making GUIs, I decided to create 2048 as it was a game that used different aspects of GUI creation. I then continued to make customizations such as allowing any sized grid to be made along with a score tracker that can be saved for each size

      - layout: top-middle
        title: Miscellaneous School Projects
        quote: >
          If you want to view the code in my various school projects, contact me so I can give access
        description: |
          At UCSD, I have worked on various school projects in many languages (Java, C, C++, ARM, and more). These projects have covered logical problem-solving, visual simulations, and other smaller projects. However, due to privacy issues and to prevent plagiarism, I can not publicly display the code, but I can directly share it to those that are interested.
          
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
